/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ChaptersChapterIdRouteImport } from './routes/chapters.$chapterId'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as LessonsNewRouteImport } from './routes/lessons.new'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersChapterIdRoute = ChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsNewRoute = LessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/lessons/': typeof LessonsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/lessons': typeof LessonsIndexRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/lessons/': typeof LessonsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/settings'
    | '/today'
    | '/chapters/$chapterId'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/students/$studentId'
    | '/subjects/$subjectId'
    | '/lessons/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/settings'
    | '/today'
    | '/chapters/$chapterId'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/students/$studentId'
    | '/subjects/$subjectId'
    | '/lessons'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/settings'
    | '/today'
    | '/chapters/$chapterId'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/students/$studentId'
    | '/subjects/$subjectId'
    | '/lessons/'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRoute
  ChaptersChapterIdRoute: typeof ChaptersChapterIdRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  LessonsNewRoute: typeof LessonsNewRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$chapterId': {
      id: '/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/chapters/$chapterId'
      preLoaderRoute: typeof ChaptersChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/new': {
      id: '/lessons/new'
      path: '/lessons/new'
      fullPath: '/lessons/new'
      preLoaderRoute: typeof LessonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRoute,
  ChaptersChapterIdRoute: ChaptersChapterIdRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  LessonsNewRoute: LessonsNewRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
